Merge v1.15.0 into umbrel

diff --git a/docker/my-dojo/bitcoin/Dockerfile b/docker/my-dojo/bitcoin/Dockerfile
--- a/docker/my-dojo/bitcoin/Dockerfile
+++ b/docker/my-dojo/bitcoin/Dockerfile
@@ -1,13 +1,14 @@
-FROM    debian:buster-slim
+FROM    debian:buster-slim AS builder
 
 
 #################################################################
 # INSTALL BITCOIN
 #################################################################
-ENV     BITCOIN_HOME        /home/bitcoin
 ENV     BITCOIN_VERSION     22.0
 ENV     BITCOIN_URL         https://bitcoincore.org/bin/bitcoin-core-22.0
-ENV     BITCOIN_FILE        bitcoin-22.0-x86_64-linux-gnu.tar.gz
+ENV     BITCOIN_FILE_AMD64  bitcoin-22.0-x86_64-linux-gnu.tar.gz
+ENV     BITCOIN_FILE_ARM64  bitcoin-22.0-aarch64-linux-gnu.tar.gz
+ENV     BITCOIN_FILE_PPCLE  bitcoin-22.0-powerpc64le-linux-gnu.tar.gz
 ENV     BITCOIN_SHASUMS     SHA256SUMS
 ENV     BITCOIN_SHASUMS_ASC SHA256SUMS.asc
 
@@ -18,30 +19,53 @@ ENV     KEYS1 71A3B16735405025D447E8F274810B012346C9A6 01EA5486DE18A882D4C268459
 # keys to fetch from keys.openpgp.org
 ENV     KEYS2 637DB1E23370F84AFF88CCE03152347D07DA627C 82921A4B88FD454B7EB8CE3C796C4109063D4EAF
 
-ARG     BITCOIND_LINUX_UID
-ARG     BITCOIND_LINUX_GID
-ARG     TOR_LINUX_GID
-
 
 RUN     set -ex && \
         apt-get update && \
-        apt-get install -qq --no-install-recommends ca-certificates dirmngr gosu gpg gpg-agent wget python3 && \
+        apt-get install -qq --no-install-recommends ca-certificates dirmngr gosu gpg gpg-agent wget && \
         rm -rf /var/lib/apt/lists/*
 
 # Build and install bitcoin binaries
 RUN     set -ex && \
         cd /tmp && \
-        gpg --batch --keyserver keyserver.ubuntu.com  --recv-keys $KEYS1 && \
-        gpg --batch --keyserver keys.openpgp.org  --recv-keys $KEYS2 && \
+        arch="$(dpkg --print-architecture)"; arch="${arch##*-}"; \
+        case "$arch" in \
+          'amd64') \
+            FILE="$BITCOIN_FILE_AMD64"; \
+            ;; \
+          'arm64') \
+            FILE="$BITCOIN_FILE_ARM64"; \
+            ;; \
+          'ppc64el') \
+          	FILE="$BITCOIN_FILE_PPCLE"; \
+          	;; \
+          *) echo >&2 "error: unsupported architecture '$arch' (likely packaging update needed)"; exit 1 ;; \
+        esac; \
+        gpg --batch --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys $KEYS1 && \
+        gpg --batch --keyserver hkps://keys.openpgp.org:443 --recv-keys $KEYS2 && \
         gpg --list-keys | tail -n +3 | tee /tmp/keys.txt && \
         gpg --list-keys $KEYS | diff - /tmp/keys.txt && \
         wget -qO "$BITCOIN_SHASUMS" "$BITCOIN_URL/$BITCOIN_SHASUMS" && \
         wget -qO "$BITCOIN_SHASUMS_ASC" "$BITCOIN_URL/$BITCOIN_SHASUMS_ASC" && \
-        wget -qO "$BITCOIN_FILE" "$BITCOIN_URL/$BITCOIN_FILE" && \
+        wget -qO "$FILE" "$BITCOIN_URL/$FILE" && \
         gpg --batch --verify "$BITCOIN_SHASUMS_ASC" "$BITCOIN_SHASUMS" && \
         sha256sum --ignore-missing --check "$BITCOIN_SHASUMS" && \
-        tar -xzvf "$BITCOIN_FILE" -C /usr/local --strip-components=1 --exclude=*-qt && \
+        tar -xzvf "$FILE" -C /usr/local --strip-components=1 --exclude=*-qt && \
         rm -rf /tmp/*
+
+FROM    debian:buster-slim
+
+ENV     BITCOIN_HOME        /home/bitcoin
+
+ARG     BITCOIND_LINUX_UID
+ARG     BITCOIND_LINUX_GID
+ARG     TOR_LINUX_GID
+
+COPY    --from=builder /usr/local/ /usr/local/
+
+RUN     set -ex && \
+        apt-get update && \
+        apt-get install -qq --no-install-recommends python3
 
 # Create groups bitcoin & tor
 # Create user bitcoin and add it to groups
